Page.create(title: "Welcome", content: "content", page_title: "page title", slug: "welcome", page_description: "page description")
Page.create(title: "NterOne Privacy Policy", content: "content", page_title: "page title", slug: "privacy_policy", page_description: "page description")
Page.create(title: "NterOne Terms and Conditions", content: "content", page_title: "page title", slug: "terms_conditions", page_description: "page description")
Page.create(title: "About NterOne", content: "content", page_title: "page title", slug: "about", page_description: "page description")
Page.create(title: "Executive Bios", content: "content", page_title: "page title", slug: "executive_bios", page_description: "page description")
Page.create(title: "Instructor Bios", content: "content", page_title: "page title", slug: "instructor_bios", page_description: "page description")
Page.create(title: "Press Index", content: "content", page_title: "page title", slug: "press_index", page_description: "page description")
Page.create(title: "Industry Index", content: "content", page_title: "page title", slug: "industry_index", page_description: "page description")
Page.create(title: "Vendor Index", content: "content", page_title: "page title", slug: "vendor_index", page_description: "page description")
Page.create(title: "Testimonials", content: "content", page_title: "page title", slug: "testimonials", page_description: "page description")
Page.create(title: "Consulting", content: "content", page_title: "page title", slug: "consulting", page_description: "page description")
Page.create(title: "Partners", content: "content", page_title: "page title", slug: "partners", page_description: "page description")
Page.create(title: "Labs", content: "content", page_title: "page title", slug: "labs", page_description: "page description")
Page.create(title: "NterOne Gives Back", content: "content", page_title: "page title", slug: "gives_back", page_description: "page description")
