source 'https://rubygems.org'

ruby '2.3.0'

gem 'acts_as_tree'
gem 'authorizenet'
gem 'autonumeric-rails'
gem 'aws-sdk-rails'
gem 'axlsx'
gem 'axlsx_rails'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'bootstrap-select-rails'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.43'
gem 'bower-rails'
gem 'canonical-rails'
gem 'carrierwave', '~> 0.10.0'
gem "celluloid", github: 'celluloid/celluloid', submodules: true
gem 'cocoon'
gem 'coffee-rails', '~> 4.0.0'
gem 'country_select'
gem 'csv-importer'
gem 'devise_invitable'
gem 'devise', '~> 3.5.6'
gem 'dumper'
gem 'enumerize', '~> 0.11.0'
gem 'exception_notification', github: 'smartinez87/exception_notification', branch: 'master'
gem 'figaro'
gem 'font-awesome-rails'
gem 'friendly_id'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails', '~> 4.0.3'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'kaminari'
gem 'mini_magick'
gem 'momentjs-rails', '>= 2.9.0'
gem 'non-stupid-digest-assets'
gem 'parsley-rails'
gem 'passenger'
gem 'pg'
gem 'public_activity'
gem 'pundit', '~> 1.0.1'
gem 'rack-rewrite', '~> 1.5.0'
gem 'rails', '4.2.6'
gem 'rails-i18n'
gem 'rails-settings-cached'
gem 'react-rails', '2.2.1'
gem 'recaptcha', require: 'recaptcha/rails'
gem 'remotipart'
gem 'roo'
gem 'rubyzip'
gem 'sass-rails', '~> 5.0.3'
gem 'search_cop'
gem 'seedbank'
gem 'select2-rails', '4.0.3'
gem 'sidekiq'
gem 'sidetiq'
gem 'simple_form'
gem 'sitemap_generator'
gem 'slack-notifier'
gem 'slim', '~> 3.0.3'
gem 'smart_listing'
gem 'sprockets-rails', '~> 2.3.1'
gem 'truncate_html'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'whenever'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'wysiwyg-rails', '2.6.2'
gem 'zip-zip'

group :development do
  gem 'annotate'
  gem 'better_errors', '~> 2.1.1'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'letter_opener'
  gem 'meta_request', '~> 0.3.4'
  gem 'rails-erd'
  gem 'traceroute'
end

group :development, :test do
  gem 'bullet'
  gem "capistrano-db-tasks", require: false
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'capistrano-ssh-doctor'
  gem 'capistrano', '~> 3.5.0'
  gem 'dotenv-rails'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec', '4.7.3'
  gem 'guard'
  # gem 'pry-byebug', '~> 3.1.0'
  gem 'pry-rails', '~> 0.3.4'
  gem 'quiet_assets'
  gem 'spring-commands-rspec'
  gem 'spring'
  gem 'awesome_print'
end

group :doc do
  gem 'sdoc', require: false
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'ffaker', '~> 2.1'
  gem 'rspec-rails', '= 3.5.0.beta3'
  gem 'rspec', '= 3.5.0.beta3'
  gem 'shoulda-matchers', require: false
end
