source 'https://rubygems.org'

ruby '2.2.1'

gem 'authorizenet'
gem 'autonumeric-rails'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'bootstrap-select-rails'
gem 'bootsy'
gem 'canonical-rails'
gem 'carrierwave', '~> 0.10.0'
gem 'cocoon'
gem 'coffee-rails', '~> 4.0.0'
gem 'country_select'
gem 'csv-importer'
gem 'devise', '~> 3.5.1'
gem 'devise_invitable'
gem 'enumerize', '~> 0.11.0'
gem 'exception_notification'
gem 'figaro'
gem 'friendly_id'
gem 'jbuilder', '~> 1.2'
gem 'jquery-rails', '~> 4.0.3'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails', '~> 5.0.5'
gem 'kaminari'
gem 'mini_magick'
gem 'parsley-rails'
gem 'pg'
gem 'public_activity'
gem 'pundit', '~> 1.0.1'
gem 'rails', '4.2.0'
gem 'rack-rewrite', '~> 1.5.0'
gem 'remotipart'
gem 'roo', '~> 2.1.0'
gem 'sass-rails', '~> 5.0.3'
gem 'sidekiq'
gem 'simple_form'
gem 'sitemap_generator'
gem 'slack-notifier'
gem 'slim', '~> 3.0.3'
gem 'sprockets-rails', '~> 2.3.1'
gem 'truncate_html'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'whenever'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

group :development do
  gem 'annotate'
  gem 'better_errors', '~> 2.1.1'
  gem 'binding_of_caller', '~> 0.7.2'
  gem 'letter_opener'
  gem 'meta_request', '~> 0.3.4'
  gem 'pry-byebug', '~> 3.1.0'
  gem 'pry-rails', '~> 0.3.4'
  gem 'rails-erd'
  gem 'traceroute'
end

group :doc do
  gem 'sdoc', require: false
end

group :test do
  gem 'database_cleaner', '~> 1.4.1'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'faker', '~> 1.4.3'
  gem 'rspec-rails', '~> 3.3.1'
end

group :development, :test do
  gem 'bullet'
  gem 'capistrano'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'dotenv-rails'
end
