# config/app.yml for rails-settings-cached
defaults: &defaults
  aws_s3_access_key_id: "AKIAJ57ZDYLSWNFV6HAQ"
  aws_s3_secret_access_key: "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"
  aws_s3_region: "us-west-2"
  aws_s3_bucket: "nterone-backup"
  aws_s3_path: "nterone"
  aws_s3_files_keep: 10

  current_hostname: "<%= `hostname`.strip %>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
