default: &default
  adapter:  "postgresql"
  host:     "www.nterone.com"
  username: "pguser"
  password: "qwe123"
  database: "db1_prod"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
